name: Build

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone SwiftShader repository
        run: |
          git clone --depth 1 https://github.com/google/swiftshader.git

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git

      - name: Build SwiftShader
        run: |
          cd swiftshader
          cd build
          cmake ..
          cmake --build . --parallel 4
          ./vk-unittests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: swiftshader-build
          path: ./swiftshader/build
