name: Build

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone SwiftShader repository
        run: |
          git clone --depth 1 https://github.com/google/swiftshader.git swiftshader-src
          ls -al

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git

      - name: Build SwiftShader
        run: |
          mkdir build
          cd build
          cmake ../swiftshader-src
          cmake --build . --parallel
          ./vk-unittests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: swiftshader-build
          path: ./build
